name: Deploy Backend to cPanel

on:
  push:
    branches:
      - master
    paths:
      - 'DailyDiction-Backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DailyDiction-Backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, bcmath, intl

      - name: Install Production Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: BRUTAL CLEANUP (Hapus File Development)
        run: rm -rf .git .github tests README.md

      - name: UPLOAD SCP (Jalur VIP + Bawa Sandi)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "DailyDiction-Backend"
          target: "/home/dailydic/daily-backend/"
          strip_components: 1

      - name: Run Optimize & Migration di Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            cd /home/dailydic/daily-backend/
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache